export const activityModel = {
    name: 'Lunch Run',
    distance: 8623.8,
    moving_time: 2385,
    elapsed_time: 2451,
    total_elevation_gain: 64.1,
    type: 'Run',
    workout_type: 0,
    utc_offset: -300,
    start_latlng: { lat: 36.19684, lng: -94.141843 },
    end_latlng: { lat: 36.197252, lng: -94.142645 },
    location_city: 'Springdale',
    location_state: 'Arkansas',
    location_country: 'United States',
    location_country_code: 'us',
    map: {
        id: 'a5051241105',
        polyline:
            'gu|{Epar}PGBc@GKHGNKRU~@DD@b@ANDJRLXALGR@BEZMTCnA@d@TS`EAz@DX@pBKvD?h@MlB?h@FfAGh@GLGDq@Di@Ca@OS?KJMf@CXBN@^CRAj@BrACn@?x@@r@@HAa@CVCFUNa@Bu@E[Fo@AaAG_A?[Gq@DsA?i@G{BAaAG}ADSGm@CeBCc@Dc@@w@G]@y@CQ@UHKHINEXAf@RlBCr@CP?lBC`@EN@^BTI`B?fDCbA@pAGl@AnAM^EXIxB?r@I^KVEXJx@?f@Kr@HXFHBPDxC?REXSXOFM@O?OEMSAO@iAAUOOO?EDILIlAUp@c@VQTYRkA`@i@t@Wd@GFODc@A_@GYIg@@sA]e@DmAVK@GCMKAc@JwABgAPmA?SEOEGc@I[OKMGS[WMUG_AAk@BW@E?{@@SAGEEOBQHm@Na@@}@O{@?a@Cm@?wDK}BHWCM@KJ]f@g@j@Qh@g@n@K\\MjAGVa@x@SPg@LKLGVEx@M\\MFOBU@GCOK[Ku@o@GSIg@@UJ}@`@gAd@eALQj@yAVa@T}@N]RSb@QPC~@En@IDCFM@IAc@E_@BMBGDCr@KR?XEb@MFGFW?GGOCWCCIQMc@Ig@Cc@NULCj@INQHYNqAJWAc@EISOUY_@Yc@QEAg@BQCWU}@uAGWSk@MUEQCm@Bm@U_E@c@J_@TONBj@IL?r@H^EZ?bALl@Eh@DPA^IjABfBU^@b@JLJ\\Hj@AZEx@o@^OPGLDDDH@TEZONQh@a@TCZMl@IXMLOPONe@Xi@J[f@y@r@wCXa@PMPUDMBg@Jm@JWRMDGJ_@\\{@j@iCLiBJa@N[^g@Pa@p@aA@SC[Qo@Gg@@QFSFMNKTKZE|@Y\\]Lk@Ai@Eg@@MDWd@q@JIRKx@Il@SRUV_@`@QR?b@GTEZMd@ARK\\Mj@C|@LLHXBb@ARCj@g@RIv@i@X]ZQ^GR?PDT@b@Cj@BPCT@XCTGd@_@n@y@UOP]`@_@@GLg@`@mCRk@PKLMHAZDn@_@TEHFDNDp@D^DLNN\\LNJZnA@PAxAAJEHEKAr@CL_@`@KTAP@fDCJEb@@j@Cd@Bj@Ax@EhADl@?LGXGvDG\\QFYCUDq@A[Dc@Oq@E',
        resource_state: 3,
        summary_polyline:
            'gu|{Epar}PGBc@GKHGNKRU~@DD@b@ANDJRLXALGR@BEZMTCnA@d@TS`EAz@DX@pBKvD?h@MlB?h@FfAGh@GLGDq@Di@Ca@OS?KJMf@CXBN@^CRAj@BrACn@?x@@r@@HAa@CVCFUNa@Bu@E[Fo@AaAG_A?[Gq@DsA?i@G{BAaAG}ADSGm@CeBCc@Dc@@w@G]@y@CQ@UHKHINEXAf@RlBCr@CP?lBC`@EN@^BTI`B?fDCbA@pAGl@AnAM^EXIxB?r@I^KVEXJx@?f@Kr@HXFHBPDxC?REXSXOFM@O?OEMSAO@iAAUOOO?EDILIlAUp@c@VQTYRkA`@i@t@Wd@GFODc@A_@GYIg@@sA]e@DmAVK@UOAc@JwABgAPmA?SEOEGc@I[OKMGS[WMUG_AAk@BW@E?wAEEOBQHm@Na@@}@O{@?a@Cm@?wDK}BHWCM@KJ]f@g@j@Qh@g@n@K\\MjAGVa@x@SPg@LKLGVEx@M\\MFOBU@GCOK[Km@g@KOKi@AULgA`@gAd@eALQj@yAVa@T}@N]RSb@QPC~@En@IDCFM@IAc@E_@BMBGDCr@KR?XEb@MFGFW?GGOCWCCIQMc@Ig@Cc@NULCj@INQHYNqAJWAc@EISOUY_@Yc@QEAg@BQCWU}@uAGWSk@MUEQCm@Bm@U_E@c@J_@TONBj@IL?r@H^EZ?bALl@Eh@DPA^IjABfBU^@b@JLJ\\Hj@AZEx@o@^OPGLDDDH@TEZONQh@a@TCZMl@IXMLOPONe@Xi@J[f@y@r@wCXa@PMPUDMBg@Jm@JWRMDGJ_@\\{@j@iCLiBJa@N[^g@Pa@p@aA@SC[Qo@Gg@@QFSFMNKTKZE|@Y\\]Lk@Ai@Eg@@MDWd@q@JIRKx@Il@SRUV_@`@QR?b@GTEZMd@ARK\\Mj@C|@LLHXBb@ARCj@g@RIv@i@X]ZQ^GR?PDT@b@Cj@BPCT@XCTGd@_@n@y@UOP]`@_@@GLg@`@mCRk@PKLMHAZDn@_@TEHFDNDp@D^DLNN\\LNJZnA@PAxAAJEHEKAr@CL_@`@KTAP@fDCJEb@@j@Cd@Bj@Ax@EhADl@?LGXGvDG\\QFYCUDq@A[Dc@Oq@E',
    },
    average_speed: 3.616,
    max_speed: 9.5,
    elev_high: 405.2,
    elev_low: 372.1,
    weather: {
        conditions: ['Clear'],
        windDirection: 5,
        cloudCover: 0,
        minTemp: 10.9,
        maxTemp: 10.9,
        precip: 0,
        solarRadiation: 706,
        dewPoint: -8.3,
        humidity: 25.25,
        visibility: 16,
        windSpeed: 21.6,
        heatIndex: null,
        snowDepth: 0,
        maxPressure: 1035.9,
        minPressure: 1035.9,
        snow: 0,
        windGust: 31.7,
        windChill: null,
    },
    timezone: '(GMT-06:00) America/Chicago',
    best_efforts: [
        {
            name: '400m',
            start_index: 177,
            end_index: 258,
            elapsed_time: 98,
            distance: 400,
        },
        {
            name: '1/2 mile',
            start_index: 513,
            end_index: 693,
            elapsed_time: 209,
            distance: 805,
        },
        {
            name: '1k',
            start_index: 881,
            end_index: 1103,
            elapsed_time: 259,
            distance: 1000,
        },
        {
            name: '1 mile',
            start_index: 1469,
            end_index: 1840,
            elapsed_time: 429,
            distance: 1609,
        },
        {
            name: '2 mile',
            start_index: 1076,
            end_index: 1829,
            elapsed_time: 870,
            distance: 3219,
        },
        {
            name: '5k',
            start_index: 548,
            end_index: 1729,
            elapsed_time: 1364,
            distance: 5000,
        },
    ],
    strava_id: 5051241105,
    month: 4,
    year: 2021,
};